---
- hosts: all
  become: true

  tasks:

#  - name: install wget
#    yum:
#      name: wget
#      state: latest
#  - name: download node exporter
#    shell: cd /tmp/ && wget https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz

#  - name: Extract tar.gz into /tmp/
#    unarchive:
#          src: '/tmp/{{item}}'
#          dest: /tmp/
#          remote_src: yes
#    with_items:
#          - node_exporter-0.17.0.linux-amd64.tar.gz


  - name: copy source target.json
    shell: cp -p  /etc/prometheus/targets.json /tmp/targets.json
    
      
 #  - name: download source target.json
 #   get_url: 
 #     url: https://raw.githubusercontent.com/alagesh146/prometheus_targets/master/targets.json
 #     dest: /tmp/targets.json
 #     mode: 0755
  - name: download csvtojson.py
    get_url: 
      url: https://raw.githubusercontent.com/alagesh146/prometheus_targets/master/csvtojson.py
      dest: /tmp/csvtojson.py
      mode: 0755
  - name: download csv file
    get_url: 
      url: https://raw.githubusercontent.com/alagesh146/prometheus_targets/master/node_exporter.csv
      dest: /tmp/node_exporter.csv

      
      
  - name: Run a script with arguments
    shell: cd /tmp && python csvtojson.py
    
    
  - name: Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version
    copy:
      src: /tmp/targets.json
      dest: /etc/prometheus/targets.json
      remote_src: yes
      owner: prometheus
      group: prometheus
      backup: yes
   
  
 #   shell: cp /tmp/node_exporter-0.17.0.linux-amd64/node_exporter /usr/local/sbin/
 # - name: remove tar files
 #   shell: rm -f /tmp/node_exporter-0.17.0.linux-amd64.tar.gz*
 # - name: remove diectory
 #   shell: rm -r /tmp/node_exporter-0.17.0.linux-amd64


  
  
  
  
#    shell: cd /tmp/ && wget https://raw.githubusercontent.com/alagesh146/Node-exporter/master/node-exporter.service
#  - name: move systemd startup file to systemd folder
#    shell: mv /tmp/node-exporter.service /etc/systemd/system/
#  - name: remove temp files

    

