---
- hosts: all
  become: true

  tasks:
  
  - name: create temp direcory
    file:
     path: /tmp/ansible
     state: directory
     mode: 0755
  
  - name: clear old files
    shell: rm -rf /tmp/ansible/*
    
  - name: copy source target.json
    shell: cp -p  /etc/prometheus/targets.json /tmp/ansible/targets.json
    
      
 #  - name: download source target.json
 #   get_url: 
 #     url: https://raw.githubusercontent.com/alagesh146/prometheus_targets/master/targets.json
 #     dest: /tmp/targets.json
 #     mode: 0755
  - name: download csvtojson.py
    get_url: 
      url: https://raw.githubusercontent.com/alagesh146/prometheus_targets/master/csvtojson.py
      dest: /tmp/ansible/csvtojson.py
      mode: 0755
  - name: download csv file
    get_url: 
      url: https://raw.githubusercontent.com/alagesh146/prometheus_targets/master/node_exporter.csv
      dest: /tmp/ansible/node_exporter.csv

      
      
  - name: Run a script with arguments
    shell: cd /tmp/ansible && python csvtojson.py
    
    
  - name: Copy a new "ntp.conf file into place, backing up the original if it differs from the copied version
    copy:
      src: /tmp/ansible/targets.json
      dest: /etc/prometheus/targets.json
      remote_src: yes
      owner: prometheus
      group: prometheus
      backup: yes
   
  


    

